### ISSUE TITLE
Custom initialization script

### ISSUE THREAD

**Issue by Limych** [ludeeus/container#141]
Please add the ability to execute a custom shell script stored in `.devcontainer/` right after the container is initialized.

It is impossible to do without this, for example, in the case of testing a custom component, which requires a library from a temporarily private repository.

**Comment by ludeeus** [comment]
You define that with `postCreateCommand` https://code.visualstudio.com/docs/remote/devcontainerjson-reference

**Comment by Limych** [comment]
The problem is that I am NOT using VisualStudio at all.

The container is automatically created on a test machine.

You did a great job that it itself takes all the necessary settings. The only thing missing is the ability to run a small script right after that so that it picks up the repository access token from the settings, and then downloads the missing library.

**Comment by Limych** [comment]
I will add. This script needs to be run INSIDE the container.

**Comment by ludeeus** [comment]
I'm confused, you are using the devcontainer for integration without using devcontainer and yet you still refrence `.devcontainer`?

**Comment by Limych** [comment]
Yes, it looks strange, but it is.

I am not using VirtualStudio. When doing this, I am using `integration_blueprint`. I wrote a small script that, using exactly the same settings, creates a docker container. But all this is done from under Linux.

Note that it is very convenient to work:
```bash
./devcontainer start
./devcontainer stop
./devcontainer down
```

At the same time, now a situation has arisen that I am developing a new integration, which I can only test on a remote test machine. Under these conditions, it is inconvenient to deploy a test assembly because of this "trifle": every time I have to manually install a fresh version of the library from a private repository on a remote machine inside the container.

Making this little script runnable will automate the deployment of the test build to that machine.

I suppose this feature could also be useful to someone else for other purposes.

**Comment by ludeeus** [comment]
Why not just make a Dockerfile for it?

```dockerfile
FROM ghcr.io/ludeeus/devcontainer/integration:stable

COPY .devcontainer/startupscript /tmp/startupscript
RUN /tmp/startupscript
```

That is the correct way to solve this issue, I don't think the container on its own should run arbitrary scripts not provided in this repo.
