### ISSUE TITLE
Integration container on m1 mac

### ISSUE THREAD

**Issue by mazerte** [ludeeus/container#248]
Hi @ludeeus 👋 !

thanks for your awesome work here! I currently try to help on [this project](https://github.com/UI-Lovelace-Minimalist/UI) with the `devContainer` but it's very slow on my mac because the container is only compiled for `amd64`. I see by reading your code that your are able to publish `arm64` base images for `alpine`. I guess you are no far to publish the `integration` container in `arm64`.

I'm not a Docker expert by any means and I don't fully understand your code so I couldn't figure out how to create a PR for this sorry.

Can you help me?

**Comment by ludeeus** [comment]
All devcontainers are Debian based and limited to amd64, there are currently no plans to change that.

**Comment by mazerte** [comment]
Thanks for your quick answer. In fact isn't true that all the devContainers are Debian based in the [Minimalist-UI](https://github.com/UI-Lovelace-Minimalist/UI/blob/main/.devcontainer/devcontainer.json#L2) we are using the `alphine` version.

I try to build it on my laptop but without succeed, so I deep dive a bit and tweak couple versions and everything work fine 🎉 !

It's up to you to make it available in your project but just for the record and if someone face the same issue, I share here the `Dockerfile` use to create the container.

```
FROM alpine:3.15

ENV CONTAINER_TYPE=integration
ENV DEVCONTAINER=True

COPY rootfs/common /

RUN  \
    apk add --no-cache  \
        bash=5.1.8-r0 \
        ffmpeg-dev=4.4.1-r2 \
        gcc=10.3.1_git20211027-r0 \
        g++=10.3.1_git20211027-r0 \
        git=2.34.1-r0 \
        jpeg-dev=9d-r1 \
        libc-dev=0.7.2-r3 \
        libffi-dev=3.4.2-r1 \
        make=4.3-r0 \
        openssh=8.8_p1-r1 \
        openssl-dev=1.1.1l-r8 \
        py3-pip=20.3.4-r1 \
        python3-dev=3.9.7-r4 \
        python3=3.9.7-r4 \
        zlib-dev=1.2.11-r3 \
        py3-sqlalchemy=1.4.26-r0 \
        tzdata=2021e-r0 \
        libpcap=1.10.1-r0 \
    && python3 -m pip install --no-cache-dir -U  \
        pip \
        setuptools \
        wheel \
    && python3 -m pip install --no-cache-dir -U  \
        black==20.8b1 \
        pylint==2.6.0 \
    && chmod +x /usr/bin/container \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && mkdir -p /config/custom_components \
    && rm -rf /var/cache/apk/* \
    && find /usr/local \( -type d -a -name test -o -name tests -o -name '__pycache__' \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' \; \
    && rm -fr /tmp/* /var/{cache,log}/*

RUN \
    apk add --no-cache \
        ruby \
        unzip \
```

Thanks for the template by the way.

PS: you can close the issue if you want

**Comment by ludeeus** [comment]
But but but, it is Debian?
<https://github.com/ludeeus/container/blob/main/containerfiles/Devcontainer.containerfile> Dockerfile
<https://github.com/ludeeus/container/blob/main/containerfiles/devcontainer/integration/config.json> Instructions
<https://github.com/ludeeus/container/runs/4924661653?check_suite_focus=true> Latest build

**Comment by mazerte** [comment]
I move these `apt` lines in the dockerfile to make the `post-create` script compatible with both

**Comment by mazerte** [comment]
Hi @ludeeus! I did more research (I wasn't rely up to date with dev-containers, sorry about) and in fact Apple Silicon work well with debian dockers.

```
# [Choice] Debian version (use bullseye or stretch on local arm64/Apple Silicon): bullseye, buster, stretch
```

I think you are using `buster` on the `integration` container and isn't available for `arm64` but `bullseye` is 😄 .

So up to you but it could make sense also for the project because most of us use Home Assistant on Raspberry so on `arm` architecture.

**Comment by ludeeus** [comment]
It's 11.2 so (bullseye) <https://github.com/ludeeus/container/blob/main/containerfiles/debian/base/config.json#L6>
But that does not matter, as I stated there are currently no plans to add multiarch images for the devcontainers.
