### ISSUE TITLE
Cannot start devcontainer on GitHub Codespaces

### ISSUE THREAD

**Issue by iMicknl** [ludeeus/container#259]
Thanks for providing a devcontainer! It has been a great help in the past time to develop a custom component, making it easy for new contributors to join your existing project.

I would like to develop on GitHub Codespaces, however I am not able to run the devcontainer. The Home Assistant Core devcontainer runs like a charm, thus that makes me very jealous 😉.

Probably related to https://github.com/ludeeus/container/pull/228, however I wonder if I am perhaps pulling the wrong container image, which doesn't contain the fix. I am trying to set this up for https://github.com/iMicknl/ha-nest-protect.

Container definition:
```json
// See https://aka.ms/vscode-remote/devcontainer.json for format details.
{
	"image": "ghcr.io/ludeeus/devcontainer/integration:latest",
	"name": "ha-nest-protect",
	"context": "..",
	"appPort": [
		"8123:8123"
	],
	"containerEnv": {
		"WORKSPACE_DIRECTORY": "/workspaces/ha-nest-protect"
	},
	"postCreateCommand": "container install && pip install -r requirements_dev.txt && pre-commit install && pre-commit install-hooks",
	"extensions": [
		"ms-python.python",
		"github.vscode-pull-request-github",
		"github.copilot",
		"ms-python.vscode-pylance"
	],
	"settings": {
		"files.eol": "\n",
		"editor.tabSize": 4,
		"terminal.integrated.defaultProfile.linux": "bash",
		"terminal.integrated.profiles.linux": {
			"zsh": {
				"path": "/bin/bash"
			}
		},
		"python.analysis.autoSearchPaths": false,
		"python.linting.pylintEnabled": true,
		"python.linting.enabled": true,
		"python.linting.pylintArgs": [
			"--disable",
			"import-error"
		],
		"python.formatting.provider": "black",
		"editor.formatOnPaste": false,
		"editor.formatOnSave": true,
		"editor.formatOnType": true,
		"files.trimTrailingWhitespace": true,
		"python.linting.mypyEnabled": true,
		"python.defaultInterpreterPath": "/usr/local/bin/python",
		"python.formatting.blackPath": "/usr/local/bin/black",
		"python.linting.banditPath": "/usr/local/bin/bandit",
		"python.linting.flake8Path": "/usr/local/bin/flake8",
		"python.linting.mypyPath": "/usr/local/bin/mypy",
		"python.linting.pycodestylePath": "/usr/local/bin/pycodestyle",
		"python.linting.pylintPath": "/usr/local/bin/pylint",
		"python.sortImports.path": "/usr/local/bin/isort",
	}
}
```

In my .devcontainer folder, I also have a configuration.yaml file.

**Error:**
```
@iMicknl ➜ /workspaces/ha-nest-protect (main ✗) $ container start
Copy configuration.yaml
Symlink the custom component directory
Start Home Assistant
Unable to find configuration. Creating default one in /config
Unable to create default configuration file /config/configuration.yaml
Configuration file: False
Unable to find configuration. Creating default one in /config
Unable to create default configuration file /config/configuration.yaml
2022-03-02 10:24:56 ERROR (MainThread) [homeassistant.bootstrap] Error getting configuration path
make: *** [/opt/container/makefiles/integration.mk:2: start] Error 1
```

**Comment by ludeeus** [comment]
https://github.com/ludeeus/container/pull/228 is not related.

**Comment by ludeeus** [comment]
`ghcr.io/ludeeus/devcontainer/integration-debian:latest` does not exist.
`ghcr.io/ludeeus/devcontainer/integration:latest` does

**Comment by iMicknl** [comment]
My bad, I copied my latest test configuration. I have been using `ghcr.io/ludeeus/devcontainer/integration:latest` when I encountered this error. I did change the first post to reflect the right value.

**Comment by iMicknl** [comment]
Thanks @ludeeus, what would be the best way to test out your latest changes? I tried changing the file on my devcontainer and than run `container install`, but it seems that this won't do the job.

**Comment by ludeeus** [comment]
rebuild.

**Comment by iMicknl** [comment]
Rebuilding will also get the old version of `opt/container/helpers/common/paths.sh`, thus I guess I will need to have a look how to fully build this from source in my Codespaces. 

Otherwise I will just wait for the next release :).

**Comment by ludeeus** [comment]
`:latest` is updated on each commit.

**Comment by iMicknl** [comment]
Are you sure? Looking at https://github.com/ludeeus/container/pkgs/container/devcontainer%2Fintegration, it seems it was last updated 1 month ago (also for the :latest tag). I tried to pull `ghcr.io/ludeeus/devcontainer/integration:latest`, but I can verify that this does not have the change to `patsh.sh`.

Thanks for looking into this, if I get this working, this will make my life a lot easier while developing custom integrations.

**Comment by ludeeus** [comment]
maybe deploy script is wrong, it should build.
Don't have time to look at that this week.
You can do `nano /opt/container/helpers/common/paths.sh` and change manually

**Comment by iMicknl** [comment]
No hurry, thanks for your fix already! I indeed tried to change the path directly, but I will have a better look and otherwise build it from source for now.

**Comment by ludeeus** [comment]
The way I tested my fix was with a codespace container of your PR in your repo, so I know using nano there directly work ;)
