### ISSUE TITLE
Persistent hass config

### ISSUE THREAD

**Issue by amosyuen** [ludeeus/container#261]
Thanks for your great work on this container. One inconvenience I've noticed when using this for custom component development is that everytime I need to update the devcontainer, the hass config instance data is wiped and I need to re-setup hass again. Is there a way to save the hass data locally say in a "/hass" folder and mount it in so that it will persist across devcontainer updates?

**Comment by ludeeus** [comment]
Yes, just mount it to `/config`

**Comment by amosyuen** [comment]
Could you clarify how that is done? I normally know how that is done with docker, but with your custom cli `container start` I didn't see any documentation on how to mount a folder

**Comment by ludeeus** [comment]
It's a devcontainer feature, not a custom CLI feature
<https://code.visualstudio.com/docs/remote/devcontainerjson-reference> look for `mounts`
