### ISSUE TITLE
Update the container

### ISSUE THREAD

**Issue by Hellowlol** [ludeeus/container#263]
![image](https://user-images.githubusercontent.com/1214134/159128912-6204012d-0bc0-4380-8169-f03ee66f5b97.png)
hasnt been updated for a while and i get a git 128 error. It was merged a fix in january but it don't seems like that's included in the container

https://github.com/custom-components/integration_blueprint/issues/71

**Comment by ludeeus** [comment]
Update your devcontainer.json to use `ghcr.io/ludeeus/devcontainer/integration:stable`
