### ISSUE TITLE
Two Enhancements: "Integration + Python Library" and "Include Home Assistant Pylint Plugins"

### ISSUE THREAD

**Issue by elahd** [ludeeus/container#270]
Hi @ludeeus: I'm proposing two enhancements to your Home Assistant integration development container. I can do the work to build this, just looking for sign off before I commit to doing the work.

1. **Integration + Python Library:** Many HA integration developers work on their integration and its associated python library side-by-side. It would be great if the devcontainer could pull down the associated library via git and install it via pip in editable mode (a.k.a. setuptools [development mode](https://setuptools.pypa.io/en/latest/userguide/development_mode.html)).
2. **Include Home Assistant Pylint Plugins:** [Home Assistant provides custom Pylint plugins](https://github.com/home-assistant/core/tree/dev/pylint/plugins) to help validate code. These plugins are specific to each version of Home Assistant. Integration developers using pylint can also use these plugins when developing, but keeping them up to date is a pain--they change monthly. It would be great if the devcontainer could extract the pylint/plugins folder when installing Home Assistant and place it in a consistent location (e.g.: /ha-dev/pylint/plugins) for referencing from pyproject.toml.

Thoughts?

**Comment by ludeeus** [comment]
Both you can already do by adjusting the `.devcontainer.json` file (specifically the `postCreateCommand` key).
This is one example of what you can do:
<https://github.com/hacs/integration/blob/main/.devcontainer.json#L4>
<https://github.com/hacs/integration/blob/main/Makefile#L8>

For 1) Personally, I don't like that approach, as I want to keep things as separate as possible.
For 2) Moving that here will not change the fact that they always change, that will force me to update and adjust this container more frequently.

Thanks for your suggestions, but I do not think this is the place for it :+1:

**Comment by elahd** [comment]
Understood on the first item.

For the second, the update would be dynamic and handled via container script. I'd add the below to the script at https://github.com/ludeeus/container/blob/main/container/helpers/common/homeassistant/set-version.sh:

```shell
git_dir="/tmp/ver"
dev_dir="/ha-dev"
repo_url="https://github.com/home-assistant/core.git"

mkdir -p "$git_dir"

if [ "$(git -C "$git_dir" config --get remote.origin.url)" == "$repo_url" ]; then
    git -C "$git_dir" checkout tags/$version
else
    git clone "$repo_url" --branch "$version" --single-branch "$git_dir"
fi

mkdir -p "$dev_dir"

if [ "$(readlink "$dev_dir"/pylint)" != "$dev_dir"/pylint ]; then
    ln -sf /tmp/ver/pylint /ha-dev/pylint
fi
```
