### ISSUE TITLE
The unauthenticated git protocol is no longer supported

### ISSUE THREAD

**Issue by Limych** [ludeeus/container#292]
When I try to initialize devcontainer I get an error:
```
ERROR: Command errored out with exit status 128: git clone -q git://github.com/home-assistant/home-assistant.git /tmp/pip-req-build-rr1_lab5 Check the logs for full command output.
```

Detailed log:
```
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

Please, replace `git://` to `https://` in code and update docker images on DockerHub.

**Comment by ludeeus** [comment]
Use https://github.com/ludeeus/container/pkgs/container/devcontainer%2Fintegration

**Comment by Limych** [comment]
I've try just now. There are same error...

**Comment by Limych** [comment]
Another people have the same errors with devcontainer:
https://github.com/custom-components/integration_blueprint/issues/71
