### ISSUE TITLE
container start terminated with exit code: 1

### ISSUE THREAD

**Issue by amosyuen** [ludeeus/container#304]
I don't think I changed anything recently, and it worked fine a month or two ago, but when I went to run the container recently I got this error:

>  *  Executing task: container start 
> 
> Copy configuration.yaml
> Symlink the custom component directory
> Start Home Assistant
> 2022-08-22 05:15:09.897 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tplink_deco which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 
>  *  The terminal process "/bin/bash '-c', 'container start'" terminated with exit code: 1. 
>  *  Terminal will be reused by tasks, press any key to close it. 

If I delete all my custom component files, the same problem happens but without the warning message for the custom component.

Any idea what's wrong? Or how to get more error ouput?

**Comment by amosyuen** [comment]
So seems that running `container upgrade` didn't help, but then I tried running `container check` and that seemed to fix the problem for me. Though it is concerning that no error output was given when it was failing.

**Comment by ludeeus** [comment]
If something is wrong then your home assistant is not working properly.
Those commands only trigger home assistant commands
