### ISSUE TITLE
How to add breakpoints in custom integration code ?

### ISSUE THREAD

**Issue by jmcollin78** [ludeeus/container#310]
Hello,

I'm developping a custom integration and for debugging purpose I wanted to be able to add some breakpoints in my code.

Is that possible when using the following image:

"image": "ghcr.io/ludeeus/devcontainer/integration:latest",

I try to add :
debugpy:
   start: true
   wait: false
   port: 5678

in my configuration.yaml. 

The debugger starts well, connect to local instance without problem but never stops to the breakpoints I give.

I try modifying this configuration without success in my launch.json:
```
{
      // Example of attaching to local debug server
      "name": "Python: Attach Local",
      "type": "python",
      "request": "attach",
      "port": 5678,
      "host": "localhost",
      "justMyCode": false,
      "pathMappings": [
        {
          "localRoot": "${workspaceFolder}",
          "remoteRoot": "."
        },
        {
          "localRoot": "${workspaceFolder}/custom_component/versatile_thermostat",
          "remoteRoot": "/config/custom_component/versatile_thermostat"
        }
      ]
    },
```
Maybe this config is not good but I can't find out how to configure this.

Any help would be greatly appreciated

**Comment by ludeeus** [comment]
AFAIK that's not possible.
With that said please do not use this, it was created long ago because there was nothing else.
Microsoft provide good containers now, that's what I use myself.

**Comment by ludeeus** [comment]
`mcr.microsoft.com/vscode/devcontainers/python:0-3.10-bullseye` is the one I use.
HA itself uses `mcr.microsoft.com/vscode/devcontainers/python:0-3.10` <https://github.com/home-assistant/core/blob/dev/Dockerfile.dev#L1>

**Comment by jmcollin78** [comment]
I suppose the HA code is not installed in the image and I will have to download it manually (and refresh it regurlarly which was automated in your image).

**Comment by ludeeus** [comment]
Yes, maybe someone could make a VSC feature for it.

Anyway, it's far better using that one, even if it's not a full replacement OOTB

**Comment by jmcollin78** [comment]
Ok many thanks for all this informations. A last question before leaving : have a you a example Github repo with the devcontainer.json and the launch.json working ?

**Comment by ludeeus** [comment]
not launch.json, but hacs/integration uses devcontainer.json at least
